package com.studyplanner.model;

import jakarta.persistence.*;
import lombok.*;

/**
 * StudySession - OOP Entity Class
 *
 * Represents a single study session in the generated timetable.
 * Each session belongs to a Subject and has:
 * - A specific date for scheduling
 * - Allocated study hours
 * - A topic to focus on (derived from the Subject's topic list)
 * - Completion status for progress tracking
 *
 * Generated by PlannerManager based on subject priority and exam proximity.
 */
@Entity
@Table(name = "study_sessions")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class StudySession {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "user_id", nullable = false)
    private Long userId;

    @Column(name = "subject_id")
    private Long subjectId;

    @Column(name = "subject_name", nullable = false)
    private String subjectName;

    @Column(nullable = false)
    private String date; // "YYYY-MM-DD"

    @Column(nullable = false)
    private Double hours;

    @Builder.Default
    private Boolean completed = false;

    @Column(nullable = false)
    private String priority; // "High", "Medium", "Low"

    private String topic;

    @Column(name = "icon_key")
    private String iconKey;

    /**
     * Returns a human-readable description of this session
     */
    public String getDescription() {
        if (topic != null && !topic.isBlank()) {
            return String.format("Study %s: %s (%.1f hours)", subjectName, topic, hours);
        }
        return String.format("Study %s (%.1f hours)", subjectName, hours);
    }
}
